galaxy_info:
  author: Moustafa Medhat
  description: "Nginx Web Server role for CentOS/Ubuntu"
  company: ""
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: CentOS
      versions: ["7","8","9"]
    - name: Ubuntu
      versions: ["18.04","20.04","22.04"]
  galaxy_tags: ["nginx","web","selinux"]
dependencies: []

