---
# tasks file for web-server
#
    - include_tasks: redhat.yaml
      when: ansible_facts['os_family'] == "RedHat"

    - include_tasks: debian.yaml
      when: ansible_facts['os_family'] == "Debian"

    - include_tasks: config.yaml
